# fly.toml app configuration file generated for flylinks-backend-weathered-pond-9344 on 2024-10-06T13:02:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flylinks-backend-weathered-pond-9344'
primary_region = 'ewr'

kill_signal = "SIGTERM"
kill_timeout = 30

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = 'flylinks_backend_data'
  destination = '/flylinks/data'
  initial_size = "30GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
